version: '3.7'
services:
  backend:
    build:
      context: ./backend
    volumes:
      - ./backend/app:/opt/app/app
      - ./backend/test:/opt/app/test
    ports:
      - 5000:5000
    command: uvicorn --reload --workers 1 --host 0.0.0.0 --port 5000 app.app:app

